logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

springwolf:
  docket:
    info:
      title: ${spring.application.name}
      version: 1.0.0
    servers:
      kafka-server:
        protocol: kafka
        host: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}